leftnav:
- identifier: 7927ccfa-638c-b336-d185-b8452a1676d1
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: e20fdeaf-bb7c-6abd-304e-611d29b9d0f4
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: fec9a6bc-fcc5-7367-b0cc-9417831b4ec8
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 244fc3ef-bca4-38e2-65d0-334dfc1a6c23
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 78bcf319-229f-9192-d8f1-5eb107ebdaf4
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
